- defaults:
    link:
        create: true
        link: true

- clean: ['~']

- link: 
    ~/.bash:
    ~/.bashrc:
        force: true
    ~/.shell:

- shell:
    - command: echo "source ./bash_profile" >> ~/.bash_profile
      stdin: false
    - [git submodule sync --recursive, 'Synching submodules']
    - [git submodule update --init --recursive, 'Updating submodules']
    - echo "Dotfiles installation complete!"