name: Dotfiles Tests

on:
  pull_request:
    branches:
      - main

jobs:
  dotfiles-tests:
    runs-on: ubuntu-24.04
    # act does not support ubuntu-24.04 yet so use this when running locally
    # runs-on: ubuntu-latest

    steps:

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      # Install the Dotfiles
      - name: Install Dotfiles
        run: |
          ./install

      # Run Dotfiles Tests
      - name: Run Dotfiles Tests
        run: |
          source ~/.bashrc
          histclear
          